services:

  mysql_polling:
    image: mysql:8.0
    container_name: mysql_polling_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: polling_db
      MYSQL_USER: user_polling
      MYSQL_PASSWORD: a@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: